name: nightly
on:
  schedule:
    - cron: '0 1 * * *'
  # can be run manually on https://github.com/rhinstaller/anaconda-webui/actions
  workflow_dispatch:
    inputs:
      compose_id:
        description: 'Compose ID to test'
        required: true
jobs:
  trigger:
    environment: 'fedora-wiki'
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Trigger the latest compose scenario
        run: |
          mkdir -p ~/.config/cockpit-dev
          echo "${{ github.token }}" >> ~/.config/cockpit-dev/github-token
          mkdir -p ~/.openidc
          echo "${{ secrets.WIKITCMS }}" >> ~/.openidc/oidc_wikitcms.json
          if [ -z "${{ github.event.inputs.compose_id }}" ]; then
            export TEST_COMPOSE=$(curl -s https://kojipkgs.fedoraproject.org/compose/rawhide/latest-Fedora-Rawhide/COMPOSE_ID)
          else
            export TEST_COMPOSE=${{ github.event.inputs.compose_id }}
          fi
          make test-compose
